services:
  - type: web
    name: wedding-invitation
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn wedding_invitation.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: pRI1De1BYigviqXLgXUi8ToVmO3tbp1DX6depQF2dbrVMFuM9hrDqzpH_XcsXjImLm4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: wedding-invitation.onrender.com